### ISSUE TITLE
`match_numbers()` should take a `redist_map` or `pop` input

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#117]
Currently, it seems to rely on a `prec_pop` attribute which isn't standard to `redist_plans` objects. 
https://github.com/alarm-redist/redist/blob/136771ed8573f2e77d34a6bf01aa28f2b59898ed/R/tidy.R#L312

It would make more sense to allow for a `pop` input, either as a `redist_map` or as an integer vector.

**Comment by christopherkenny** [comment]
Fixed this for plans_diversity(). Will replicate commit: https://github.com/alarm-redist/redist/commit/47c454669e229c120d9b1b954f0982d376169551

**Comment by CoryMcCartan** [comment]
@christopherkenny When we add new args, e.g. for `plans_diversity()`, they have to be added at the end, or existing code breaks. Can you move `total_pop` in `plans_diversity()` to the end and default it to `attr(plans, "prec_pop")` or something?
