### ISSUE TITLE
`add_constr_group_inv_hinge`

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#119]
For state legislative districts, the opposite of hinge is useful and common enough to warrant a formal constraint.

**Comment by CoryMcCartan** [comment]
Opposite as in a penalty for exceeding a setpoint?

**Comment by christopherkenny** [comment]
Yes, exactly. Hinge but the other direction. For relatively small districts, that seems particularly useful

**Comment by kosukeimai** [comment]
I also think that the hinge in both directions could be useful as an option here though one can just impose the two together (this is particularly relevant when one wishes multiple districts to be in a certain range).
