### ISSUE TITLE
`redist_mergesplit_parallel` does not track MH acceptance of each chain

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/redist#124]
It would be helpful to have some indication of the metropolis hastings acceptance rate stored in the object. It could be either an overall acceptance rate across all the chains, or a vector of chain-specific acceptance rate.

from the example page:

```
data(fl25)
fl_map = redist_map(fl25, ndists=3, pop_tol=0.1)
fl_sim_ms = redist_mergesplit(fl_map, nsims=100)
fl_sim_pl = redist_mergesplit_parallel(fl_map, nsims=100, chains=100)

str(fl_sim_ms)
str(fl_sim_pl) # "mh_acceptance" is not an attribute
```

**Comment by kosukeimai** [comment]
I think it's important to store chain-specific acceptance ratio

**Comment by christopherkenny** [comment]
#121 implements @kuriwaki
