### ISSUE TITLE
`redist.plot.map` showing non-district boundaries

### ISSUE THREAD

**Issue by rodrigomontalegre** [alarm-redist/redist#125]
I've created simulted maps and would like to plot some of these without boundaries. I'm using census block groups as the building blocks for these maps. If I use the following function, the boundaries of these census block groups are still plotted.

`redist.plot.map(shp = maps,
plan = plan_number, 
boundaries = FALSE)`
 
Is this a bug or am I doing something wrong? If this isn't a bug, please point out my error.

**Comment by christopherkenny** [comment]
Hello. Thank you for pointing this out. Are you using `ggsave()`? If I just look in RStudio, it looks fine, but once I use `ggsave()`, it adds the lines back in. I've patched that for dev.

**Comment by rodrigomontalegre** [comment]
Boundaries don't show up in the file when using `ggsave()`.
