### ISSUE TITLE
enumpart not set up/linked correctly in latest version

### ISSUE THREAD

**Issue by hamiltonw** [alarm-redist/redist#128]
I'm trying to run enumpart, though I get the error 

Error: Failed to execute '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/redist/enumpart/enumpart' (No such file or directory)

in the latest version.

**Comment by christopherkenny** [comment]
Hello @hamiltonw. Have you run `redist.init.enumpart()` first? The particular error typically indicates that the command was not run after fresh install or that it failed in some way. If you've already run it, could

**Comment by hamiltonw** [comment]
I did not; I ran it and all works again, thanks!
