### ISSUE TITLE
How to create adjacency list for non-contiguous geographic areas

### ISSUE THREAD

**Issue by apantazi** [alarm-redist/redist#133]
I'm dealing with Florida congressional maps and trying to figure out what the best way is to coerce an adjacency object for non-contiguous parts of the state (namely, islands across the state and particularly near the Florida Keys). Do I have to edit the adjacency object by hand or are there easier ways to do it?

**Comment by CoryMcCartan** [comment]
Yep, you'll have to manually fix it. However, the [`geomander` package](https://www.christophertkenny.com/geomander/) from our own @christopherkenny provides some functions that make this super easy.  `suggest_neighbors()` and `add_edge()` in particular should be useful.
