### ISSUE TITLE
rmapshaper in Suggests - usage?

### ISSUE THREAD

**Issue by ateucher** [alarm-redist/redist#136]
Hello - I'm the author of `rmapshaper`, which is listed under `Suggests` in `redist`'s dependencies, however I can't seem to find anywhere that it's used in `redist` - can you point me to where it is used?

I ask because I have to check reverse dependencies when I prepare a CRAN release, and if this dependency is not necessary I'd like to drop it from the checks.

Thanks!

**Comment by CoryMcCartan** [comment]
Hi! We use `rmapshaper` on the dev side to prep shapefiles, and also recommend it to users as a way to simplify geometries. But there's no hard dependency anywhere in the code or vignettes.  You should be good to drop it from your reverse dependency checks.

**Comment by ateucher** [comment]
Great, thanks!
