### ISSUE TITLE
`redist_mergesplit()` new default warmup in 4.0 is a breaking change

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#143]
```
data(iowa)
ia <- redist_map(iowa, existing_plan = cd_2010, pop_tol = 0.01)
redist_mergesplit(ia, nsims = 100)
```
results in
```
Error in `redist_mergesplit()`:
! `nsims` must be greater than `warmup`.
Run `rlang::last_error()` to see where the error occurred.
```
Should revert or create new warnings for the change.

**Comment by CoryMcCartan** [comment]
Yep, this is intentional.  The warning there is new to reflect this and the documentation explains why.

**Comment by christopherkenny** [comment]
It's an error not a warning

**Comment by CoryMcCartan** [comment]
Oh sorry that's what I meant.  You can't trust the results at all with fewer than 100 warmup draws.  We don't stop people from setting `warmup=0` if they really want but we do initialize `warmup` to a correct default value.  And obviously it's impossible for the algorithm to run if `nsims<warmup`
