### ISSUE TITLE
`first_plan()` feature to match `last_plan()`

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#147]
A symmetric feature here would be useful.

```r
first_plan(plans)
```

**Comment by CoryMcCartan** [comment]
would it get the first plan in the object or the first _sampled_ plan?

**Comment by CoryMcCartan** [comment]
Not quite sure the use case.  Ref plans (& the init plan for MCMC) are right at the top and labeled nicely.  last_plan() gets you the end of shortburst/ an MCMC chain / a random SMC plan (since those are shuffled)
