### ISSUE TITLE
Helper or `filter` argument for submaps

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#156]
Let's make it a little easier to update populations without using `attr<-`() ...

**Comment by CoryMcCartan** [comment]
more detail?

**Comment by christopherkenny** [comment]
The idea here would be that if you have a `redist_map` and want to subset it, you could set something like `.preserve_pop = TRUE` within the filter if the population bounds should be preserved as-is. (Maybe it would be named `.update_pop = TRUE` by default if that better conveys what would happen.) Right now it tries to do it intelligently using the `existing_col`, but that isn't always the intended behavior.

**Comment by CoryMcCartan** [comment]
Addressed by fff0dc4a
