### ISSUE TITLE
Feature request: allowing hard constraint for splitting counties/administrative entities?

### ISSUE THREAD

**Issue by martial00120** [alarm-redist/redist#161]
Hi
How about adding the possibilty to have a hard constraint for splitting counties? In Germany, we have a higher tolerance for population deviation in the US (+/- 25%) but we optimize more in the direction of not splitting counties/county-equivalent areas. So how about opening up the possibility that at max .... counties can be split or that a county can at max be split k times? Then your project could be more helpful for the German application.

Sebastian Goderbauer, a Operations Research scientiest has published a proposal for redistricting in Germany, which optimizes mainly on this constraint, but his Code is unfortunately not available (and his thesis is in German).

**Comment by CoryMcCartan** [comment]
We do have a hard split constraint! It can be accessed with the `county=` argument to `redist_smc()`.  That will guarantee fewer splits than the number of districts minus 1 (though in practice you will often get many samples with fewer splits).  If you need even fewer splits, you have two options:

- Combine `county=` with a soft county constraint (see <https://alarm-redist.org/redist/reference/constraints.html>)
- Merge all the units (e.g. precincts) in one or more counties together before running the sampler. The extreme version of this is to do your sampling at the county level, which will guarantee zero splits.  See <https://alarm-redist.org/redist/articles/map-preproc.html#merging> for an example of this technique.

Hope that helps.

**Comment by martial00120** [comment]
Ok, thank you! I could not try out your solutions yet.
