### ISSUE TITLE
Enquiries about adding non-US maps and data interfaces

### ISSUE THREAD

**Issue by KenHok** [alarm-redist/redist#165]
First, I would like to express the admiration and gratitude of the redist package for the tremendous contribution of scholars of electoral studies to understanding and researching the topic of redistricting!

I am an electoral politics researcher from China and I have tried to use this toolkit to analyse the fairness of gerrymandering in Hong Kong, Taiwan and Malaysia and to simulate fairer gerrymandering results through this tool. However, I found that the toolkit basically only imports the US census and maps for each tier, and cannot add map files from other countries or regions. I have also tried to import and adapt it using a geoprocessing toolkit in R such as the sf package, but unfortunately this did not work.

In order to facilitate the extension of this research on electoral politics to other regions with direct elections and to promote fairness and equity in global elections, I would like the authors of the redist package to make the following improvements: **include an interface or function for importing electoral maps from other countries or regions (Non-America) in the redist package, and provide an introduction page and documentation with map files and data file standards that can be imported. data files that can be imported, so that researchers can easily use this powerful toolkit.**

I understand that this is a bit much, but as a researcher in electoral politics, I can't help but admire this excellent tool every time I see it, and hope that it can be used to give other developing regions a fairer and more equitable electoral environment.

Looking forward to hearing from the author!

And good luck!

**Comment by shomiyazaki** [comment]
Dear @KenHok ,

Thank you so much for your inquiry.
My name is Sho Miyazaki, and I am a member of the ALARM project working on Japanese redistricting analysis. Also, I am currently working on the Malaysian gerrymandering analysis with other scholars. 
As you point out, it is important and valuable to analyze the fairness of electoral districts using simulation methods, not only for the US but also for other countries for comparative analysis.

We appreciate your feedback and will work on incorporating these functions soon.
Meanwhile, I suggest you check out our GitHub repository for the Japanese redistricting project.
https://github.com/alarm-redist/japan
Hopefully, the codes in this repository work as a reference for your need — the Japanese census shapefiles require us to clean before using the simulations.
One of the useful examples might be Yamaguchi prefecture.
https://github.com/alarm-redist/japan/tree/main/analyses/35_yamaguchi
Please check the `01_prep_35_yamaguchi.R` file, as well as the source code of  `download_shp()` and `clean_jcdf()` in this repository.
Also, this function (https://r-spatial.github.io/sf/reference/valid.html) in the `sf` package might be helpful.

Best, 
Sho

**Comment by KenHok** [comment]
Dear Shomiazki.

Very pleasantly surprised to find such a prompt response to the above question, and first of all, I would like to express my sincere thanks for your thorough reply!

I am delighted that the ALARM project team has been able to consider and improve the importation of other maps, which will be an important achievement in advancing the fairness of elections and the usefulness of redistricting in other countries, and I am sure that other researchers in electoral politics will express the same expectation.

I will be taking the lead myself in trying to analyse the maps that I would like to use for the redist package analysis based on the responses you have provided. I will also ask questions here if difficulties or obstacles arise in the process and proceed in a direction that will advance the improvement of this toolkit. I hope that this process will provide some appropriate assistance in updating the redist package.

With best regards

Ken Hok
