### ISSUE TITLE
`summary.redist_plans()` should return diagnostics for mergesplit without summary stats

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#167]
Currently it returns NULL if there are no additional columns but it should return other diagnostics.

**Comment by CoryMcCartan** [comment]
what other diagnostics?

**Comment by christopherkenny** [comment]
MH acceptance, diversity, etc. Similar to what SMC does when there are no columns. Right now MS just returns NULL if there are no columns to estimate r-hats for.
