### ISSUE TITLE
Deprecation warnings for 4.2.0 not useful

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#171]
Currently, they point to a whole different package, rather than pointing to the correct replacement.

Example:
```
ℹ In argument: `egap = partisan_metrics(map, "EffGap", rvote, dvote)`.
Caused by warning:
! 'partisan_metrics' is deprecated.
Use 'redistmetrics' instead.
See help("Deprecated")
```

This should point to `part_egap()`. It could be nice to also give some of the syntax, like `part_egap(redist::pl(), map, rvote, dvote)` since those can be inferred at that point.

**Comment by CoryMcCartan** [comment]
Can't infer `map`/`shp` object name, so just pointing people to the correct function(s)

Closed by ce17ec4
