### ISSUE TITLE
Weird `add_constr_custom()` behaviors

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#173]
- [ ] If a call to a function is present using `::`, you get the following warning.
```
Error in `rlang::as_string()`:
! Can't convert a call to a string.
```
Workaround: Define the required function in the global environment before using it, like `colMins <- matrixStats::colMins` before declaring the custom constraint.

- [ ] Sub-`redist_map`s after filtering fail if you rely on the district number and the numbers are not sequential. On an example Iowa map, filter out district 2 and then try to subset to access district `2`, causing a NaN issue.
Workaround: renumber the `existing_col` when you create the map

**Comment by christopherkenny** [comment]
`::` issue fixed by explicitly using a child environment.

**Comment by CoryMcCartan** [comment]
Can you elaborate on the 2nd issue?

_Shouldn't_ accessing indices that don't exist cause problems?
