### ISSUE TITLE
Filtering all the rows of a `redist_map` errors

### ISSUE THREAD

**Issue by CoryMcCartan** [alarm-redist/redist#182]
When we check the population bounds on a filtered `redist_map` we are implicitly assuming that at least one row exists.  Need to handle the case where 0 rows are returned.

```r
redist:::ld_ia()

dplyr::filter(ia, FALSE)
#> Error in if (bounds[1] > new_tgt || bounds[3] < new_tgt) { :
#>   missing value where TRUE/FALSE needed
```

**Comment by christopherkenny** [comment]
Should it error? For comparison, is it possible to create a 0-row sf `tibble`?
