### ISSUE TITLE
Wait time for running SMC without an existing plan

### ISSUE THREAD

**Issue by anyadougherty** [alarm-redist/redist#189]
Please briefly describe your problem and what output you expect. 
For a project I was trying to run SMC based on a shapefile without an existing plan in an attempt to reduce bias. I could not get even 2 simulated plans after allowing it to run for hours. The function never stopped running after an extended period of time I had to terminate it. I was curious if there was a reason this was taking so long to run or if it is just too complex of a request.

Sampling setup:
I used the get_alarm data for Pennsylvania, here is a code of the code I was using.

# prep geo data
geo_pa = get_alarm(
  "PA",
  epsg = 3857
)
adj_geo = redist.adjacency(geo_pa)

# create initial plan
set.seed(1)
rd_map = redist_map(shp_data, existing_plan = NULL, total_pop = pop, ndists = 17, pop_tol = 0.01, adj = adj_geo)

# create random plans
rd_plans = redist_smc(rd_map, nsims=2)

< copy any constraints objects here >
```

```
<insert the output of summary(plans) here>
```

<insert a picture of `plot(map)` here>

**Comment by CoryMcCartan** [comment]
What version of `redist` do you have?

Can you share the output of `redist_smc(rd_map, nsims=2, verbose=TRUE)`? If it hangs you can terminate after a minute or two and paste the output here.

Also, FYI, unlike `redist_mergesplit` or other MCMC algorithms, using an `existing_plan=` does not change the output of the algorithm at all or create any "bias."  The existing plan functionality is included as a convenient way to compare the results of the simulations to real-world plans.

**Comment by anyadougherty** [comment]
I have redist_4.2.0, but now the function seems to be working fine. I am unsure of what happened. Thank you.
