### ISSUE TITLE
Allow for additional customization in constraints

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#24]
Constraints are currently very limited in scope. Some rewriting for the C++ is necessary to allow for new constraints beyond the most common choices

**Comment by JacobCoblentz** [comment]
happy to help on this. thinking about being able to optimize for partisan balance.

**Comment by jpcoblentz** [comment]
thinking about incorporating partisan metrics.

**Comment by CoryMcCartan** [comment]
Subsumed under #76
