### ISSUE TITLE
Better names for example data

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/redist#41]
The names of the example data in Florida is not intuitive and slows down a first time user. Can they be more streamlined and renamed?

- [x] It is not clear that `fl25`  is a shape file. Better: `fl25_shp`?
- [x] Why 25 - I think it's better to explain that in the fl25 help page and name the actual place in Florida thi is from
- [x] Why are there three versions (25, 70, 250)

- [x]  It's not clear what the purpose of `algdat*` is. Is it an intermediate output that is saved to save user's time? It doesn't seem useful in practice because, unlike a shapefile, users will not have a object like this.
- [x] Why is it called "algdat"? Doesn't seem very evocative

**Comment by christopherkenny** [comment]
1. We could rename it, though I think the better option is to augment the description a bit. `edgecut` has some improved documentation, especially relating to categories on the website.
2. 25 is a sweet spot for being able to make 3 districts in quick fashion and validate on a local machine. There isn't a real name for it, as far as I know. It was introduced in the 2014 (or maybe 2015) version of [Fifield et al. 2020a](https://www.tandfonline.com/doi/abs/10.1080/10618600.2020.1739532) and is one of the basic standards for redistricting validation. An example of its use is [Magleby and Mosesson 2018](https://www.cambridge.org/core/journals/political-analysis/article/new-approach-for-developing-neutral-redistricting-plans/31F8EB3FFB7A8F5B3F7C2171BE016D47). I can add some more information on this to the description if that is helpful to people.
3. The 25 precinct case is from the MCMC paper. The 70 and 250 precinct examples are from [Fifield et al. 2020b](https://www.tandfonline.com/doi/full/10.1080/2330443X.2020.1791773). These are not friendly for full enumerations on a local machine, but are quite useful for trying to look at more complex redistricting problems and algorithms, but still at a small enough scale to work on locally.
4.  The `algdat` family contains the full enumerations of 25 precincts into 3 districts at 10% population parity, 20% population parity, and all population parities. These predate including the `fl#` files, so the precinct.data portions were not always an overlap.  I think they still serve a purpose in having example distance matrices and segregation indices, though I'm not sure if that's as compelling anymore, as the code to recompute those parts is really fast now.
5. I think it's short for `algorithm data`, but I don't actually know.

**Comment by kuriwaki** [comment]
Thanks. I agree whatever problems I had with it can be solved by documentation, much of it what you wrote out for me. Even saying "This dataset was used in Fifield et al. 2020a" alone is really useful for the user.

If algdat* is going to be kept in, then it would be more useful for the user to show the code on _how_ such a dataset is created from a precinct file. (in a man example, a vignette, or simply as uncompiled code in `data-raw` (R packages [ch.14](https://r-pkgs.org/data.html)))
