### ISSUE TITLE
Documentation and naming for identify cores

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/redist#46]
A couple of clarification questions / suggestions on the [cores](https://github.com/kosukeimai/redist/blob/edgecut/R/cores.R) function currently in edgecut branch. I'd be happy to submit a PR if you'd like?

- [x] Per earlier discussion, I think `unfreeze = 1` is more intuitive than `within = 1`.  unfreeze = 0  clearly signals "freeze everything" and I could extrapolate from there. In contrast, saying that a core is "all precincts more than `within` edges from a district boundary" feels inverted
- [ ] The new(?) name of "identifying" cores was less intuitive than explaining it as making cores (as previous version) by freezing precincts together. [I ultimately defer to the author on this and the previous point)
- [x] An incomplete sentence in the description paragraph.
- [x] Would be worth explicitly saying what the grouping variable is going to be called `gid` and how to interpret it, what to be careful of.
- [x] Link to `redist.plot.cores` via `@seealso`?
- [x] Would be worth defining what a core is in the context of an existing district. And cite something like this NCSL [page](https://www.ncsl.org/research/redistricting/redistricting-criteria.aspx)
- [x] An example snippet

**Comment by christopherkenny** [comment]
1. Yeah, I believe we settled on `free_boundary` if my notes are correct. The current setup is `within` to match the tidy version and still needs to be updated.
2. Could you clarify what you're talking about? The function has been named `redist.identify.cores()` since it was written, so I think I'm missing something.
3-7. Addressed by commit within the edgecut branch - 17cdaa5

**Comment by kuriwaki** [comment]
Looks great. Re point 2, I meant the tidy version, where I think this was called `make_cores()`. But I see, if it's been named `redist.identify.cores()` in the CRAN versions, then makes sense not to change.

**Comment by christopherkenny** [comment]
Oh, okay. I see the point then. `redist.identify.cores` is not yet on CRAN (nor suggested to outside users) so we have free reign over the naming if you have a better suggestion. As it is not within the tidy framework, the idea behind the name is that you're identifying the cores to then you are free to group by them depending on your choice of analysis. (And potentially, users may not be simplifying if they are trying to do something very specific.)

**Comment by kuriwaki** [comment]
Ok the name `identify.cores` sounds fine to me in that case.

One last thing here. The current documentation says "Each precinct more than \code{boundary} steps away from another district gets it own group." Should it say instead "Each **contiguous group of** precincts** .. "  because otherwise, it implies each precinct gets its own group i.e. no unioning occurs?

**Comment by christopherkenny** [comment]
Updated in 3bc9d4e
