### ISSUE TITLE
total_pop should not depend on default variable name

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/redist#49]
The example for redist_map currently suggests

```
redist_map(fl25, ndists=3, pop_tol=0.05)
```

where `total_pop` implicitly takes default value `"pop"`.

I don't think `total_pop` should have a default value. Variable names naturally vary across datasets; it would be better to show in examples that one must specify the population varname in such cases.  

Otherwise, the error message for datasets without a pop variable would be confusing:

``` r
library(redist)
library(dplyr)
data(fl25)

rename(fl25, population = pop) %>% 
  redist_map(ndists=3, pop_tol=0.05)
#> Projecting to CRS 3857
#> Error: Can't subset columns that don't exist.
#> x Column `pop` doesn't exist.
```

<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Fix to be proposed in PR

**Comment by CoryMcCartan** [comment]
Definitely agree the error message should be better, so thanks for #50 .  I do think explicitness is good, but so are sensible defaults.  I'd be inclined to check the df for "pop", "total_pop", "population", etc. & if exactly 1 is present, set the population to that value. If more than 1 is present, there'd be a warning about the default selection, and if none are present, there'd be an informative error.

**Comment by kuriwaki** [comment]
I tend to think such a list of reasonable variable names is hard to anticipate. The dataset that led me to make this suggestion has CVAP, VAP, vs. total; census vs. ACS; 2010 vs. 2018.  Explicitness (at least in examples) is nice as it would prevent breaking errors if the defaults change later.

In any case I will defer to you. Your edit sounds straightforward to add to the PR, or feel free to do it separately.
