### ISSUE TITLE
Additional defaults for histograms

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/redist#54]
I have some suggestions for defaults in [`redist.plot.hist()`](https://corymccartan.github.io/redist/reference/redist.plot.hist.html).

All of them are listed as comments in the reprex below. The result is the center figure in the panel, as opposed to the original left.  

When the values are positive integers, which happens often with districts, I have additional suggestions:  Namely showing only integers on the axis labels and shifting to x > 0. I think we could detect if values are integers internally by something like `function(x) all(rlang:: is_integerish(x))`.

Some of the suggestions are close to aesthetic but others I think are important to avoid confusion. I think high priority for me are:

- y-axis `expand` to 0
- Allowing users to provide x-axis label
- integer labels when values are integers

Happy to start a PR for the items the package authors agree, if that is easier.

``` r
library(ggplot2)
suppressPackageStartupMessages(library(dplyr))
library(patchwork)

# example
suppressPackageStartupMessages(library(redist))
data(iowa)
iowa = redist_map(iowa, existing_plan = cd_2010, pop_tol = 0.05)
plans = redist_smc(iowa, nsims = 100, silent = TRUE)

distr_dev = plans %>%
  group_by(draw) %>%
  summarize(pop_dev = max(abs(total_pop / mean(total_pop) - 1)))

gg_orig <- hist(distr_dev, pop_dev) +
  labs(title = "Original")



# Proposal for all histogram graphs ----
# @param becomes a argument
qty_label = "Population Deviation"

gg_prop <- ggplot(distr_dev, aes(x = pop_dev)) +
  ggplot2::geom_vline(data = subset_ref(distr_dev), aes(xintercept = pop_dev, color = .data$draw)) +
  geom_histogram(
    # current method of finding bins looks fine
    bins = 4,
    # add outline (aesthetic preference)
    color = "white",
    # show fraction in sample, not couns
    aes(y = stat(density*width)),
    boundary = 0
  ) +
  # label accordingly
  labs(y = "Fraction of plans")  +
  # because y-axis will never be negative, cut expansion
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  scale_color_discrete("Plan") + # done in function
  # Add @param qty_label or somthing like that to allow users to add proper xlab
  labs(x = qty_label) +
  # In histogram, vertical axes don't matter / are obvious
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  labs(title = "Proposed",
       subtitle = "For Integer/Fractions")



# If values are positive integers (like county splits or number of maj.
# minority distircts), propose ADDing the following on top of the above

# https://stackoverflow.com/a/39877048
int_break <- function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1))))
set.seed(08544)
distr_int <- tibble(x = rbinom(1000, 10, 0.2))

gg_int <- ggplot(distr_int, aes(x)) +
  geom_histogram(
    # fix binwidth to 1. Cleaner interpretation
    binwidth = 1,
    color = "white",
    # Do not let the bars go x < 0.
    boundary = 0
  ) +
  # do not show decimals in the x-axis
  scale_x_continuous(breaks = int_break) +
  # rest is the same
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  labs(title = "Proposed",
       subtitle = "For Integer values")


# compare
gg_orig + gg_prop + gg_int +
  plot_layout(guides = "collect")
```

![](https://i.imgur.com/mY6RJFv.png)

<sup>Created on 2021-03-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by CoryMcCartan** [comment]
THanks for this! I'm a big fan of getting rid of the space below 0 on the y axis... I'll add that by default. 

For the x axis label, do you think a new parameter is preferable to just doing the following? 
```r
hist(distr_dev, pop_dev) +
    labs(x = "Population Deviation")
```

for the integer case, should the binwidth be 1, or 0.5, to create space between bars & emphasize the discreteness?  I've done the former but wonder if the latter makes sense.
also, should the bars be centered over the integer in this case? I think that generally makes it clearer which of the two bars an integer falls into, rather than having to check the documentation

**Comment by kuriwaki** [comment]
I see, `labs(x = ...)` sounds good. It would keep the custom function simple.

> should the binwidth be 1, or 0.5

Hadn't thought about that and I'm not sure if I have a preference either way. If binwidth = 0.5, then I guess it would be important to have the bar be centered at the integer (your point below)

> should the bars be centered over the integer in this case? I think that generally makes it clearer which of the two bars an integer falls into

* That's a good point. The risk with centering the bar at the integer is that with a bar at 0 it looks like the left half of the bar is negative, thus my suggestion of setting `geom_histogram(..., boundary = 0)`. But for other integers, I agree it makes sense to leave it at the default (I think `boundary = NULL` is the default). 
* So how about keeping the default but allowing an argument in `hist` to modify it to any number?

**Comment by christopherkenny** [comment]
See Cory's commit f7b0798
