### ISSUE TITLE
Tidy metrics broken outside of dplyr verbs

### ISSUE THREAD

**Issue by CoryMcCartan** [alarm-redist/redist#60]
Unintended consequence of internals rewrite pre-3.0 release.

Reprex courtesy of @kuriwaki 

``` r
suppressPackageStartupMessages(library(redist))
suppressPackageStartupMessages(library(dplyr))
​
data("fl250")
​
fl_map <- redist_map(fl250, ndists = 10, pop_tol = 0.02, total_pop = TotPop)
#> Projecting to CRS 3857
fl_plans <- redist_smc(fl_map, nsims = 100, silent = TRUE)
​
# this one errors
distr_compactness(fl_map, .data = fl_plans)
#> Error: `cur_data_all()` must only be used inside dplyr verbs.
​
# but this one works
fl_plans %>% mutate(compactness = distr_compactness(fl_map))
#> 100 sampled plans with 10 districts from a 250-unit map,
#>   drawn using Sequential Monte Carlo
#> With plans resampled from weights
#> Plans matrix: num [1:250, 1:100] 9 9 5 5 9 5 9 9 5 5 ...
#> # A tibble: 1,000 x 4
#>    draw  district total_pop compactness
#>  * <fct>    <int>     <dbl>       <dbl>
#>  1 1            1     78404       0.556
#> # … 
```
​
<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by christopherkenny** [comment]
@CoryMcCartan My understanding is that this is a necessary design choice to be able to use `dplyr::cur_*` functions. Perhaps the thing to do here is to check for a within-mutate environment and otherwise point it to redist.compactness?

**Comment by CoryMcCartan** [comment]
@christopherkenny This was a mistake by me to use `dplyr::cur_*` when I could have used `.data`.  Haven't ever been happy with `.data` since it's sensitive to whether you pipe in the data or just do `mutate(plans, ...)`.  

So this new PR actually recurses through the call stack to identify if you're inside a dplyr verb, and if so, gets the plans object from there.  If not then it gives the usual "must pass .data" error
