### ISSUE TITLE
Migrate to `cpp11`?

### ISSUE THREAD

**Issue by CoryMcCartan** [alarm-redist/redist#67]
Compilation times are slow.  This may cause CRAN problems down the road and immediately impacts users and developers in the form of long install times.

`cpp11` will allow for faster compilation and a smaller package size:
<https://cpp11.r-lib.org/articles/motivations.html#compilation-speed-1>

But there will be a lot of work to convert Rcpp types to cpp11 types for i/o objects, and armadillo types for internal objects.

**Comment by christopherkenny** [comment]
Perhaps this is a good 3.2 goal (August/September release?). In the meantime, it might be good to start writing new code with `cpp11` and patch older code using the existing `Rcpp` pieces. 

I don't think we can ever fully drop Rcpp due to OpenMP usage.

**Comment by CoryMcCartan** [comment]
Hmm, if we can't drop it completely then I don't think we can reap the benefits.

This is `Rmpi` stuff?  I don't think Rmpi depends on Rcpp?

**Comment by christopherkenny** [comment]
Yeah Rmpi requires the OpenMP makevars, I believe. It matters then [for this line](https://github.com/alarm-redist/redist/blob/563df7f2a651660544c3d933701c80fc6a397d89/src/Makevars#L3). Removing the OpenMP from the unix makevars would then cause problems with using Rmpi on clusters, which is where people would most likely be using MPI.

**Comment by CoryMcCartan** [comment]
But does OpenMP / Rmpi depend on Rcpp?

**Comment by kosukeimai** [comment]
@christopherkenny and @CoryMcCartan This seems a lot of work.  At least for now, we should table it off and focus on writing the documentation (i.e., paper).  The package compilation should not happen too often for a given user and so hopefully they will put up with us.

**Comment by CoryMcCartan** [comment]
Definitely; this is a long-term problem for staying on CRAN but doesn't need to be addressed right away.
