### ISSUE TITLE
upcoming sf will break redist (when using s2)

### ISSUE THREAD

**Issue by edzer** [alarm-redist/redist#71]
Hi Christopher! Please see https://github.com/r-spatial/sf/issues/1649 - pls also consider commenting there in case you run into troubles fixing this one. Looks like yours are about area estimates - there's still the possiblity to get the ellipsoidal ones through lwgeom, rather than the (now default) spherical ones from s2.

**Comment by CoryMcCartan** [comment]
Closed by #74
