### ISSUE TITLE
Delisted from CRAN

### ISSUE THREAD

**Issue by michaelcgorman** [alarm-redist/redist#79]
Just wondering if you have any idea when redist will be back on CRAN. I didn't see any discussion on other (open or closed) issues about why it was taken down or what needs to happen to get it back up.

In the meantime, is the master branch generally stable enough that an end-user would be pretty safe installing and using it straight from Github?

Thanks! Looking forward to using what you've built.

**Comment by christopherkenny** [comment]
Hi -- The master branch is generally very stable as long as you are on a non-solaris operating system. The master version is typically whatever is on CRAN most recently with any minor bug fixes that need to be tweaked.

With CRAN: It's currently having some issues with how types need to be declared within the Solaris build, which we thought were fixed, but do not appear to be. We're hoping to have that finalized soon.

**Comment by michaelcgorman** [comment]
Awesome. Thanks for the insight! I will go ahead and install from Github.
