### ISSUE TITLE
custom adj object in `redist_map`

### ISSUE THREAD

**Issue by jpredist** [alarm-redist/redist#80]
I would like to pass my own adjacency object into redist map, but I am seeing an error that says 
`Error: Input must be a vector, not a <nb> object.`

```
> redist::redist_map(sp.sample, adj = adjlist,
+                    total_pop = "Population", ndists = 11)
Projecting to CRS 3857
Error: Input must be a vector, not a <nb> object.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In redist::redist_map(sp.sample, adj = adjlist, total_pop = "Population",  :
  `pop_tol` not provided; defaulting to 1%
```

**Comment by christopherkenny** [comment]
Hi @jpredist. It sounds like you're working with spdep's nb class (perhaps with `poly2nb`). Converting it into a usable entry to `adj` should be as simple as running:
`adjlist <- lapply(adjlist, function(x){x + 0L})`
which will coerce it into a list of integer vectors.
Note: If you are using `poly2nb`, you will need to zero index it, in which case, you want to run:
`adjlist <- lapply(adjlist, function(x){x -1L})`

Without more specific information, that's what the issue looks like to me from the error message. If that doesn't fix it though, feel free to ask again with a bit more information about the inputs.

**Comment by CoryMcCartan** [comment]
Just want to add that `poly2nb` often creates some strange artefacts.  So unless there's a good reason for that function specifically, we recommend `redist.adjacency` which more robustly calculates the adjacency graph.

**Comment by jpredist** [comment]
that makes sense -- I wrote a custom function to connect islands from a nb​ object and it seems that redist​ is not recognizing the object as being fully connected even though `n.comp.nb(adj) = 1`
________________________________

**Comment by christopherkenny** [comment]
If it's helpful, the code for `is_contiguous()` is a simpler version of `geomander::check_contiguity()`. The geomander version returns more information which might shed some light on which precinct isn't being registered as connected, but is by spdep.
