### ISSUE TITLE
`enumpart` missing some partitions with non-unit weights

### ISSUE THREAD

**Issue by gabeschoenbach** [alarm-redist/redist#82]
Hi, thanks so much for this easy-to-use ZDD implementation, it's been great to play around with!

I've noticed something strange when running `enumpart` on a 4x4 grid with non-unit weights and a specified population bound. Specifically, it doesn't seem to find/count a partition that should be valid. I'm not sure whether this is an error on my part or a bug either in reading in the graph/weights or constructing the ZDD.

The graph is the [4x4 grid](https://github.com/alarm-redist/redist/files/6540342/4x4_rook.txt), with NSEW "rook" adjacencies between vertices. The [population weights](https://github.com/alarm-redist/redist/files/6540356/iowa_4_weights.txt) is a 16-vector of populations assigned to each vertex, made by roughly mapping the county-level population in the state of Iowa to a 4x4 grid. If we want to find all partitions of the grid into 4 districts where each district deviates no more than 2% from the ideal population, then we need to set the population bounds at [746,358, 776,819]. (our ideal population `I` = 3,046,355 / 4 = 761588.75, and the bounds are `I` ± 0.02*`I`).

Once you include the above files (`4x4_rook.txt` and `iowa_4_weights.txt`) in the `enumpart` directory, running
```sh
./enumpart 4x4_rook.txt iowa_4_weights.txt -k 4 -lower 746358 -upper 776819 -count
```
produces
```sh
Started
  Reading "4x4_rook.txt" ... done in 0.00s elapsed, 0.00s user, 820MB.
  #vertex = 16, #edge = 24
  GraphPartitionSpecL31 .......... <1680> in 0.00s elapsed, 0.00s user, 1068MB.
  Reduction .......... <971> in 0.00s elapsed, 0.00s user, 1120MB.
  ComponentWeightSpec ........
    Sweeping <1559> ... <1190> in 0.00s elapsed, 0.00s user, 1252MB.
    .
    Sweeping <1297> ... <0> in 0.00s elapsed, 0.00s user, 1252MB.
    .
  Done ComponentWeightSpec <0> in 0.00s elapsed, 0.00s user, 1252MB.
  Reduction <0> in 0.00s elapsed, 0.00s user, 1256MB.
  #node = 0, #solution = 0
  Counting solutions ...
    #solution = 0
  Done counting solutions in 0.00s elapsed, 0.00s user, 1260MB.
Finished in 0.00s elapsed, 0.00s user, 1268MB.
```
But there is a partition of this grid that falls within the population bounds. We found this partition through our own implementation of the `enumpart` algorithm in Julia, which matches up with your algorithm for every unit-weighted square grid we've been able to check. In component format, the 2%-deviation valid partition is
```sh
0 0 1 1 2 0 1 3 2 0 0 3 2 2 3 3
```
and visually it looks like this: ![example](https://user-images.githubusercontent.com/51930407/119525342-697e9680-bd4c-11eb-870c-1fcb068e69c8.jpeg)

This issue persists for other maximum population deviations; for example, setting a 5% max. deviation gives us the bounds [723,510, 799,667], and running enumpart with
```sh
./enumpart 4x4_rook.txt iowa_4_weights.txt -k 4 -lower 723510 -upper 799667 -count
```
also says there are 0 valid partitions, even though the following partitions are valid (note that the first partition is the same as the 2% one above, since a partition with under 2% max. pop. dev. will also be under 5%.
```sh
0 0 1 1 2 0 1 3 2 0 0 3 2 2 3 3
0 1 2 2 0 1 2 3 0 1 1 3 1 1 3 3
0 1 1 2 0 1 1 2 0 3 1 2 3 3 3 2
0 1 1 2 0 1 1 2 0 1 3 2 3 3 3 2
```

On a related note, using the ratio of the maximum district weight over the minimum gives interesting results — I don't know for sure if this is incorrect, but wanted to bring it up. If we run the following (with `ratio = 1.0`)
```sh
./enumpart weights_issue/4x4_rook.txt weights_issue/iowa_4_weights.txt -k 4 -ratio 1.0 -count
```
we see that there are 117 solutions. Increasing the ratio all the way up to 5/3 (1.6666...) keeps this answer of 117. For ratios between 1.67 - 2.0 we get 1953 solutions, and ratio = 2.0 gives us 2992. I was surprised to see the solution count stay the same for such large ratio intervals, and especially interested that the answers were 117 and 1953, which [correspond to the number of partitions of the 4x4 unit-weighted into equal-sized and equal±1-sized districts, respectively](https://mggg.org/table.html). Since this grid is _not_ unit-weighted, seeing those specific numbers seems strange to me, but would love to know what y'all think!

**Comment by CoryMcCartan** [comment]
Hi there, thanks for filing this issue.

It looks like you may be using an old build of `enumpart`? I don't think our current version has `ComponentWeightSpec` enabled.  Can you try rebuilding and confirming the problem continues?

Also, the ZDD counter does not currently use the non-unit-weight and lower-upper bound flags.  Does the algorithm still fail to replicate the Julia-generated partitions when you ask it to actually generate all the valid partitions?

In general, the enumpart code here is only supported through the R package interface, which doesn't implement some of the flags on the command-line version.  The weights and lower/upper flags in particular were sort of bolted on to allow for rejection sampling to save storage space when doing large runs.  They are not well-integrated into the rest of the enumpart code.

**Comment by gabeschoenbach** [comment]
Thanks for the quick response! If I delete the `enumpart` binary and rerun `make`, the problem continues, and `ComponentWeightSpec` is still enabled. I tried just re-cloning `redist` and making the binary from scratch, but then I get an error message that ends with:

```sh
3 warnings generated.
ld: library not found for -lpsapi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [enumpart] Error 1
```
I can send along the full output, if helpful. 

If I remove the lower/upper bound flags, `enumpart` will return 62,741 solutions which matches the Julia code, so we're all good there! It seems though that any non-unit weights pared with either lower/upper flags or the ratio constraint is causing some errors.

**Comment by CoryMcCartan** [comment]
I'm not sure about the linker error; @christopherkenny may have something to add there.  

But by design the non-unit weights with lower/upper flags only affects the generated plans and not the counting feature.  If you run `./enumpart 4x4_rook.txt iowa_4_weights.txt -k 4 -lower 746358 -upper 776819` do you still not get any plans generated?

**Comment by christopherkenny** [comment]
`-lpsapi` should be added to the makefile when run with `redist.init.enumpart()` on Windows. So very odd. Are you on Windows?

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
library(redist)
#> 
#> Attaching package: 'redist'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)

if(!file.exists(paste0(system.file('enumpart',package = 'redist'),'/enumpart'))){
  redist.init.enumpart()
}

# recreate the grid
grid <- sf::st_make_grid(x = st_sfc(st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,0))))),
                         n = 4) %>% st_as_sf()
adj <- redist.adjacency(grid)
grid$pop <- as.numeric(unlist(str_split(readLines(con = '~/Downloads/iowa_4_weights.txt'), pattern = ' ')))

#
grid %>% mutate(rn = row_number()) %>% ggplot() + geom_sf() + geom_sf_label(aes(label = rn))
```

![](https://i.imgur.com/4NMTnuZ.png)

``` r
plot(grid)
```

![](https://i.imgur.com/CAc8mUO.png)

``` r
unord <- '~/Downloads/unord'
ord <- '~/Downloads/ord'
enum <- '~/Downloads/enum'
wts <- '~/Downloads/wts'
writeLines(text = as.character(grid$pop), con = '~/Downloads/wts.dat')

redist.prep.enumpart(adj = adj, unordered_path = unord, ordered_path = ord)
#> [1] 0
redist.run.enumpart(ordered_path = path.expand(ord), out_path = path.expand(enum), ndists = 4,
                    weight_path = path.expand(wts), lower = 746358, upper = 776819)
#> [1] 0
```

<sup>Created on 2021-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I recreated your example in R, but please forgive the use of `~/Downloads/` for this.

Now, the weird thing is I do get the correct plan in my enum.dat file:
`0 0 1 1 2 0 1 3 2 0 0 3 2 2 3 3`

Where did you clone it from @gabeschoenbach?

**Comment by christopherkenny** [comment]
Sorry, it looks like a mac/unix unfriendly tag made it through to the master branch. I just removed that, which would have caused the failure on your re-clone a few minutes ago @gabeschoenbach

**Comment by christopherkenny** [comment]
If you run 
` ./enumpart 4x4_rook.txt iowa_4_weights.txt -k 4 -comp -allsols -lower 746358 -upper 776819`
it should print out the single solution.

The R code does get the partition -- for the first example (2%), it saves the single solution. The `0` indicates success, not a number of solutions.

**Comment by gabeschoenbach** [comment]
Ah, fantastic — thank you! For my understanding (because I'm hoping to scale this up as large as I can stand), under the hood is it creating a ZDD for all possible partitions of the 4x4 grid without attention to weights, and then going back through the partitions and only printing the ones that fit inside the bounds? I ask because I see the `#solutions = 62741` still in this latest output.

**Comment by christopherkenny** [comment]
Yeah, it creates the ZDD through an [efficient frontier search](https://link.springer.com/chapter/10.1007%2F978-3-319-53925-6_10). Much of the computational efficiency comes form a merging step in the search, but if it needed to keep track of populations during that process, almost no merges could occur. After double checking the C++, the number of solutions that's tracked is the total ZDD size.

If you're trying to go for a large scale, then using the `lower/upper` arguments and then counting the number of lines in an output should almost always be faster than trying to write everything to disk and subsetting after the fact.
