### ISSUE TITLE
Parallel computing recommendation

### ISSUE THREAD

**Issue by kuriwaki** [alarm-redist/redist#84]
It would be helpful to have a simple section or page in a vignette of recommendations for computing samples in parallel. 

Documentation 

- Which algorithms can and cannot be done by parallel
- Recommendations of parallelization on a normal computer, using e.g. `doParallel` or `future`
- example code

brms / stan has a ["cores" argument](https://paul-buerkner.github.io/brms/reference/brm.html) in the main function which I have found convenient, perhaps for a future idea.

**Comment by christopherkenny** [comment]
@kuriwaki Circling back to this (a lot of planning for the next few months going on right now). Would your ideal thing be a `redist_flip_parallel`, `redist_smc_parallel`, `redist_shortburst_parallel` (etc if new algs added)? Or would your ideal be an article that explains _how_ to use the parallel options in general?

**Comment by kuriwaki** [comment]
A new function was not really what I had in mind (unless writing a function is easier for you than adding an argument or adding documentation)

Ideally for my case there is a brms/rstan-like argument `cores = 4` (like I noted above) within each existing `redist_*` function.

Another alternative is a vignette about example code of how to make your own parallelization and what not to do.

I turned some specifics into checklists in my above comment.

**Comment by CoryMcCartan** [comment]
We have `mergesplit_parallel` since MCMC is easily parallelizable. But `shortburst` and `smc` not so much -- they need to share information in order to function properly.  We are looking at doing this at the C++ level, in which case it would likely be exposed to the user as a `cores=` argument. 
Closing this for now until we have a clearer direction / timeline.
