### ISSUE TITLE
Improved reporting

### ISSUE THREAD

**Issue by CoryMcCartan** [alarm-redist/redist#89]
Reporting during sampling is verbose, especially for SMC with many districts.

Suggested changes:

1. Use `cli` progress bars for iterations & splits (nested? need to evaluate), with dynamic sampling diagnostics as appropriate
2. Save sampling diagnostics and return as part of a list to R, so that they can be examined later & programmatically

**Comment by CoryMcCartan** [comment]
Part of this also involves replacing all warnings, errors, and messages with `cli_*` equivalents

**Comment by christopherkenny** [comment]
@CoryMcCartan, do we want mergesplit to return the constraint weights as part of this? Is that easily done? (Could see some projects getting use out of that.)

**Comment by CoryMcCartan** [comment]
eh that's probably pretty tricky, given how many constraints you can specify (eg what do we do if you specify two `group_hinge` constraints).  Also, the weights apply only to the districts you are merging and splitting, so those'd have to be returned too.  Unclear to me what the value in that is

**Comment by christopherkenny** [comment]
`flip_` currently gives `energy_psi` which has the product over everything. Those weights are even more constrained in terms of total change, but I guess are calculated over the _entire_ set of districts, whereas ms computes over the two districts?

**Comment by christopherkenny** [comment]
I'm highly partial to additional features rather than removing things when we have the ability to add them while reformulating (otherwise I suspect someone will ask for them a few weeks after we decide to remove them from experience).

**Comment by CoryMcCartan** [comment]
right, M-S computes things only for the 2 districts involved in the proposal
and then there's the log spanning tree term in the target, which has to be considered if you want to understand how the log prob evolves through the chain.  but calculating that slows things down a lot

`flip` can probably still calculate `energy_psi` even with the merged calculation functions, but adding it to M-S doesn't provide any analysis value, I don't think

**Comment by christopherkenny** [comment]
#121 starts this for flip
