### ISSUE TITLE
Tidy Constraint Checker -- Better Errors

### ISSUE THREAD

**Issue by christopherkenny** [alarm-redist/redist#96]
New constraints take a list input of the form:

`constraints = list(vra = list(strength = ...))`

The double list allows for flexibility on our end for extending options and cleaner input. 
However, if you forget the inner list, because we want it to work always, it doesn't error out or even warn.

**Comment by christopherkenny** [comment]
Should also point to errors when there are expectations about constraints that don't exist in SMC but do elsewhere. (#99)

**Comment by CoryMcCartan** [comment]
Fixed by our new constraints interface d3b3ce8
